language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
script:
  - npm run build
#  - yarn test
before_deploy:
  - git tag "$(date +'%Y%m%d-%H%M%S')-$(git log --format=%h -1)"
  - cd build
  - tar -zcf steder.tar.gz steder.txt
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - steder.tar.gz
  skip_cleanup: true
  on:
    branch: master
after_deploy: ../slack.sh ops "deploy steder"
notifications:
  slack:
    on_success: change
    on_failure: change
